name: Android Build and Sign (Release)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          target: android-33
          ndk: false

      - name: Decode keystore
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.keystore

      - name: Make gradlew executable
        run: |
          chmod +x ./gradlew

      - name: Build Release APK
        env:
          ANDROID_HOME: ${{ runner.temp }}/android-sdk
        run: |
          ./gradlew clean assembleRelease --no-daemon

      - name: Sign and align APK (if keystore provided)
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        run: |
          mkdir -p signed
          # locate unsigned release apk
          unsigned_apk=$(find app/build/outputs -name "*-release-unsigned.apk" | head -n 1)
          if [ -z "$unsigned_apk" ]; then
            echo "Unsigned APK not found, trying release apk..."
            unsigned_apk=$(find app/build/outputs -name "*release.apk" | head -n 1)
          fi
          echo "Unsigned APK: $unsigned_apk"
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore release.keystore -storepass "${{ secrets.KEYSTORE_PASSWORD }}" -keypass "${{ secrets.KEY_PASSWORD }}" "$unsigned_apk" "${{ secrets.KEY_ALIAS }}"
          # zipalign
          zipalign_path=$(find $ANDROID_HOME -name zipalign | head -n 1)
          if [ -z "$zipalign_path" ]; then
            echo "zipalign not found in SDK; trying build-tools"
            zipalign_path=$(find ${HOME}/.android -name zipalign | head -n 1)
          fi
          if [ -z "$zipalign_path" ]; then
            echo "zipalign not found; skipping alignment (may still be fine)"
            cp "$unsigned_apk" signed/app-release-signed.apk
          else
            $zipalign_path -v 4 "$unsigned_apk" signed/app-release-unsigned-aligned.apk || true
            jarsigner -verify -verbose -certs signed/app-release-unsigned-aligned.apk || true
            cp "$unsigned_apk" signed/app-release-signed.apk || true
          fi
      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk
          path: |
            signed/**
            app/build/outputs/apk/release/**
            app/build/outputs/apk/debug/**